from ex0 import FlameFactory, AquaFactory

if __name__ == "__main__":
    print("Testing factory")
    flameFactory = FlameFactory()
    creature1 = flameFactory.create_base()
    evolved1 = flameFactory.create_evolved()
    print(creature1.describe())
    print(creature1.attack())
    print(evolved1.describe())
    print(evolved1.attack())
    print()
    print("Testing factory")
    aquaFactory = AquaFactory()
    creature2 = aquaFactory.create_base()
    evolved2 = aquaFactory.create_evolved()
    print(creature2.describe())
    print(creature2.attack())
    print(evolved2.describe())
    print(evolved2.attack())
    print()
    print("Testing battle")
    print(creature1.describe())
    print("vs .")
    print(creature2.describe())
    print("fight!")
    print(creature1.attack())
    print(creature2.attack())
